/** Styles partagés pages Connexion / Inscription */
export const authPageStyles = {
    page: {
        display: "flex",
        minHeight: "100vh",
        fontFamily: "'Segoe UI', system-ui, sans-serif",
    },
    leftPanel: {
        flex: 1,
        background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
        position: "relative",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "48px",
        overflow: "hidden",
    },
    overlay: {
        position: "absolute",
        inset: 0,
        background:
            "url('https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80') center/cover no-repeat",
        opacity: 0.15,
    },
    leftContent: {
        position: "relative",
        zIndex: 1,
        color: "#fff",
        maxWidth: "400px",
    },
    hotelBadge: {
        display: "inline-block",
        background: "rgba(201,168,76,0.2)",
        border: "1px solid #c9a84c",
        color: "#c9a84c",
        padding: "6px 16px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: "600",
        letterSpacing: "2px",
        marginBottom: "24px",
    },
    hotelTitle: {
        fontSize: "32px",
        fontWeight: "700",
        lineHeight: "1.3",
        marginBottom: "16px",
        color: "#fff",
    },
    hotelSubtitle: {
        fontSize: "16px",
        color: "rgba(255,255,255,0.65)",
        lineHeight: "1.6",
    },
    rightPanel: {
        width: "480px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#f8fafc",
        padding: "40px 32px",
    },
    formCard: {
        width: "100%",
        maxWidth: "400px",
    },
    iconWrapper: {
        width: "64px",
        height: "64px",
        background: "linear-gradient(135deg, #c9a84c, #e8c96d)",
        borderRadius: "16px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: "24px",
        boxShadow: "0 8px 24px rgba(201,168,76,0.35)",
    },
    icon: {
        fontSize: "28px",
    },
    title: {
        fontSize: "26px",
        fontWeight: "700",
        color: "#1a1a2e",
        marginBottom: "8px",
    },
    subtitle: {
        fontSize: "14px",
        color: "#64748b",
        marginBottom: "28px",
    },
    alert: {
        background: "#fef2f2",
        border: "1px solid #fecaca",
        color: "#dc2626",
        padding: "12px 16px",
        borderRadius: "10px",
        fontSize: "14px",
        marginBottom: "20px",
        display: "flex",
        gap: "8px",
        alignItems: "center",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "20px",
    },
    fieldGroup: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
    },
    label: {
        fontSize: "13px",
        fontWeight: "600",
        color: "#374151",
        letterSpacing: "0.3px",
    },
    inputWrapper: {
        position: "relative",
        display: "flex",
        alignItems: "center",
    },
    inputIcon: {
        position: "absolute",
        left: "14px",
        fontSize: "16px",
        pointerEvents: "none",
    },
    input: {
        width: "100%",
        padding: "12px 14px 12px 42px",
        border: "1.5px solid #e2e8f0",
        borderRadius: "10px",
        fontSize: "15px",
        color: "#1a1a2e",
        background: "#fff",
        outline: "none",
        transition: "border-color 0.2s",
        boxSizing: "border-box",
    },
    inputNoIcon: {
        width: "100%",
        padding: "12px 14px",
        border: "1.5px solid #e2e8f0",
        borderRadius: "10px",
        fontSize: "15px",
        color: "#1a1a2e",
        background: "#fff",
        outline: "none",
        boxSizing: "border-box",
    },
    eyeBtn: {
        position: "absolute",
        right: "12px",
        background: "none",
        border: "none",
        cursor: "pointer",
        fontSize: "16px",
        padding: "4px",
        lineHeight: 1,
    },
    submitBtn: {
        padding: "14px",
        background: "linear-gradient(135deg, #c9a84c, #e8c96d)",
        color: "#1a1a2e",
        border: "none",
        borderRadius: "10px",
        fontSize: "15px",
        fontWeight: "700",
        cursor: "pointer",
        transition: "opacity 0.2s, transform 0.1s",
        marginTop: "4px",
        letterSpacing: "0.3px",
    },
    backLink: {
        textAlign: "center",
        marginTop: "24px",
        fontSize: "14px",
    },
    link: {
        color: "#c9a84c",
        textDecoration: "none",
        fontWeight: "500",
    },
};
